baseurl = "https://pastel.computer"
paginate = 4
title = "pastel.computer"
copyright = "Andrew Souvanlasy"
pygmentsUseClasses = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 20
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/DreStation"
    weight = 30
    [menu.main.params]
      newTab = true